controller_list:
  - name: fake_braccio_arm_controller
    type: $(arg execution_type)
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - wrist_roll_joint
      - gripper_joint
initial:  # Define initial robot poses.
  - group: braccio_arm
    pose: default